config ssh by providing private key
aiidalab/aiidalab-widgets-base pull request #110
Opened 2020-08-04 10:26 UTC by unkcpz

2020-09-16 11:23 UTC, unkcpz commented
@yakutovicha Do you have time to have a look at this, I think this works well in the server in China. Qiang configures the computer by using this, therefore merging this pr would be helpful for me to then maintain the server.

2020-09-18 21:46 UTC, yakutovicha commented
> @yakutovicha Do you have time to have a look at this, I think this works well in the server in China. Qiang configures the computer by using this, therefore merging this pr would be helpful for me to then maintain the server.

Thanks @unkcpz I will have a look ASAP. Before I do that, though, can you please fix the pre-commit failure?

2020-09-19 04:42 UTC, unkcpz commented
Sure! fixed. @yakutovicha

2020-11-03 20:57 UTC, yakutovicha reviewed
Thanks, @unkcpz. Generally, looks good to me. One thing I would like to ask is to not split `on_setup_ssh` function into two sup-parts. This leads to a lot of code duplication. Can you please merge them into one and add some `if-else` statement?

Also, I am not sure why you changed the order of the arguments in `_configure_proxy`. Is that really needed?

2020-11-07 02:40 UTC, unkcpz commented
Hi Sasha, I put the functions into one with `if-else`. Well, a little bit untidy. 
As for `_configure_proxy` I put `password` after the `password_proxy` since in setting with private key the `password`  is not set. Anyway, I change it back to the original order, and set `password` to None explicitly when using private key mode.

2020-11-08 23:24 UTC, yakutovicha reviewed
Thanks @unkcpz. 

>  I put the functions into one with if-else. Well, a little bit untidy.

Yep, I think so too. I added a couple of suggestions that would considerably reduce the `mode` branching. Can you please have a look?

2020-11-08 23:24 UTC, yakutovicha commented on aiidalab_widgets_base/computers.py
> +                self._write_ssh_config(proxycmd=proxycmd, private_key_fname=private_key_abs_fname)
I think those if statements can be avoided entirely. If I understood correctly, the behaviour is determined by the value of the `private_key_abs_fname`. If, by this time, it is `None`, then no private key will be set.

2020-11-08 23:24 UTC, yakutovicha commented on aiidalab_widgets_base/computers.py
> +        return path.basename(fname)
Can you please make this function return the full path?

2020-11-10 08:14 UTC, unkcpz commented on aiidalab_widgets_base/computers.py
> +            password = None
Good point! No reason to separate them apart. Fixed.

2020-11-10 08:14 UTC, unkcpz commented on aiidalab_widgets_base/computers.py
> +        if mode == 'private_key':
True! removed.

2020-11-10 08:17 UTC, unkcpz commented
@yakutovicha Thanks for the comments. I change the code as your suggestion. Looks more clear now. But I only test password and private_key, not sure the new changes will cause problems on 'proxy' setting.

2020-11-10 08:20 UTC, unkcpz commented
By the way, for you to clear review, I didn't rebase the last commit.

2020-11-11 10:49 UTC, yakutovicha requested changes
Thanks @unkcpz, looks good. I tested several scenarios and all seems to work properly. Please apply the last requested change and I will approve/merge. 

I think this is a good step forward.

While reviewing the PR I realized that there is some code duplication in `_configure_proxy` and `_on_setup_ssh`. But this should be a subject of a separate PR. I made an issue for that: https://github.com/aiidalab/aiidalab-widgets-base/issues/152

2020-11-11 10:49 UTC, yakutovicha commented on aiidalab_widgets_base/computers.py
> +            print(self.hostname, self.username, password, proxycmd)
```suggestion
```

Almost missed it :)

2020-11-12 02:24 UTC, unkcpz commented on aiidalab_widgets_base/computers.py
> +            print(self.hostname, self.username, password, proxycmd)
Terrible carelessness ;)

2020-11-12 08:06 UTC, yakutovicha approved these changes
Looks good, thanks @unkcpz !

2020-11-12 08:16 UTC, merged