Improved stability of smiles renderer
aiidalab/aiidalab-widgets-base pull request #117
Opened 2020-08-27 10:45 UTC by cpignedoli

We use now pybel that seems to work for more cases.
Also the search among conformers was removed being too slow

2020-08-27 11:23 UTC, yakutovicha commented
@cpignedoli, before I start reviewing can you please fix all the pre-commit issues?

2020-08-28 13:04 UTC, yakutovicha requested changes
Thanks @cpignedoli, a few suggestions/questions.

2020-08-28 13:04 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        atoms.center()
```suggestion
        atoms = Atoms(species, positions=posnew, pbc=True, cell=np.ptp(posnew, axis=0)+10)
        atoms.center()
```

2020-08-28 13:04 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        atoms.center()
Not 100% sure it will work, please try.

2020-08-28 13:04 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        #f_f.ConjugateGradients(6500, 1.0e-9)
```suggestion
```

2020-08-28 13:04 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
>          # initial cleanup before the weighted search
```suggestion
        # Initial cleanup before the weighted search.
```

2020-08-28 13:18 UTC, cpignedoli commented on aiidalab_widgets_base/structures.py
> +        pca = PCA(n_components=3)
there is no "return asemol" in the file that I pushed for PR teh funcion that i pushed is:
    @staticmethod
    def pymol_2_ase(pymol):
        """Convert pymol object into ASE Atoms."""

        species = [chemical_symbols[atm.atomicnum] for atm in pymol.atoms]
        pos = np.asarray([atm.coords for atm in pymol.atoms])
        pca = PCA(n_components=3)
        posnew = pca.fit_transform(pos)
        atoms = Atoms(species, positions=posnew)
        sys_size = np.ptp(atoms.positions, axis=0)
        atoms.pbc = True
        atoms.cell = sys_size + 10
        atoms.center()
        return atoms

2020-08-28 14:27 UTC, cpignedoli commented
I checked, the modifications work

2020-08-31 07:54 UTC, yakutovicha approved these changes
Thanks, @cpignedoli, looks good!

2020-08-31 07:54 UTC, merged