Fix code setup.
aiidalab/aiidalab-widgets-base pull request #255
Opened 2021-10-06 23:02 UTC by yakutovicha

fixes #254 

1. Make sure to not setup code if computer is not provided.
2. Gracefully handle situations when the requested code plugin
is not installed.

2021-10-07 07:39 UTC, csadorf requested changes
The computer part worked fine, but when I tried to setup a code for a non-installed plugin (I used eiger and used root to uninstall the aiida-quantumespresso plugin), nothing happened. No warning or error message or anything (see screenshot).
![Screen Shot 2021-10-07 at 09 33 21](https://user-images.githubusercontent.com/1441208/136340679-c255cfd6-16a1-4d74-9dd4-2309513a09d5.png)

2021-10-07 07:39 UTC, csadorf commented on notebooks/setup_code.ipynb
> +  {
Is there an actual change in this notebook or is this just random Jupyter shuffling?

2021-10-07 07:39 UTC, csadorf commented on aiidalab_widgets_base/computers.py
>              supplied was not found in your AiiDA database."""
```suggestion
            self.output.value = f"""Computer instance '<span style="color:red">{computer.label}</span>'
            is not configured in your AiiDA profile."""
```

2021-10-07 07:39 UTC, csadorf commented on aiidalab_widgets_base/codes.py
> +                print("Please specify a computer from your database.")
```suggestion
                print("Please specify a computer that is configured in your AiiDA profile.")
```

2021-10-07 07:39 UTC, csadorf commented on aiidalab_widgets_base/codes.py
> +            return None
```suggestion
        return plugin if plugin in self.inp_code_plugin.options else None
```

2021-10-07 11:58 UTC, yakutovicha commented
@csadorf, I tested things locally. Everything should work now. But please test it as well.

2021-10-08 08:21 UTC, csadorf requested changes
After uninstalling `aiida-quantumespresso` the "Code plugin" selection is now empty, however when clicking on "Setup code" nothing happens, just like before. I would suggest to disable the "Submit" button in case that the form is not correctly filled in.

As an aside, I did not refresh the page after uninstalling the package and the code was actually configured with the now uninstalled plugin.

2021-10-08 08:21 UTC, csadorf commented on aiidalab_widgets_base/computers.py
>              self.output.value = f"""No computer named '<span style="color:red">{computer}</span>'
Make sure to adapt the error message to the slightly adjusted on lines 918+919.

2021-10-12 15:05 UTC, csadorf commented
@yakutovicha Should I test this again?

2021-10-14 09:10 UTC, merged