SMILESWidget: Store SMILES in StructureData extras
aiidalab/aiidalab-widgets-base pull request #265
Opened 2021-11-12 18:34 UTC by danielhollas

Hi folks, here's a PR as discussed in #264. Happy to make any changes. LMK if there is a good way to write a test for this.

Closes #264

2021-11-12 18:37 UTC, danielhollas commented on aiidalab_widgets_base/structures.py
> +    def _pybel_opt(self, smiles, steps):
Unrelated: `s/smile/smiles` to make the code consistent.

2021-11-15 15:43 UTC, yakutovicha requested changes
Thanks, @danielhollas, overall looks good to me. I just have a couple of minor suggestions.

2021-11-15 15:43 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
>              return structure_node_type(ase=structure)
Just a bit shorter.

```suggestion
            structure_node = structure_node_type(ase=structure)
            if "smiles" in structure.info:
                structure_node.set_extra("smiles", structure.info["smiles"])
            return structure_node
```

2021-11-15 15:43 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +    def make_ase(self, species, positions, smiles):
We are changing the API of several methods, which is not so good, in principle. But, they should not be called outside of this class, so I would suggest making them "internal":

```suggestion
    def _make_ase(self, species, positions, smiles):
```

2021-11-15 15:43 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        return self.make_ase(species, positions, smiles)
```suggestion
        return self._make_ase(species, positions, smiles)
```

2021-11-15 15:43 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        return self.make_ase(species, positions, smiles)
```suggestion
        return self._make_ase(species, positions, smiles)
```

2021-11-15 15:43 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +    def mol_from_smiles(self, smiles, steps=10000):
Please change the method name in the other places too.
```suggestion
    def _mol_from_smiles(self, smiles, steps=10000):
```

2021-11-15 20:52 UTC, danielhollas commented
@yakutovicha thanks for the review! I implemented all the proposed changes.

2021-11-16 16:33 UTC, yakutovicha approved these changes

2021-11-16 16:33 UTC, merged

2021-11-16 16:34 UTC, yakutovicha commented
Thanks a lot, @danielhollas!