clean up dependencies requirements
aiidalab/aiidalab-widgets-base pull request #395
Opened 2022-11-26 00:14 UTC by unkcpz

`aiida-core>=2.0,<3` -> replace with `aiida-core[atomic_tools]>=2.0,<3` to include all the atomic tools installed in `lab` stack.

Therefore the following packages is installed already:
- `ase<3.20`
- `spglib~=1.16`
- `pandas~=1.0`

The following packages are even conflict and will override the deps which cause the Jupyter engine fail.
- `ipywidgets~=7.6`
- `jupyter-client<7`
- `nbconvert<6`

- `aiidalab>=21.11.2` is already pinned in the stack

`aiida-core` > 2 will lead to install `numpy~=1.19` therefore `numpy~=1.23` is installed.
- numpy~=1.17

2022-11-26 00:35 UTC, unkcpz commented
The test failed as expected, it rely on https://github.com/aiidalab/aiidalab-docker-stack/pull/333

2022-11-27 21:11 UTC, danielhollas commented
I wonder was there a specific reason for this constraint? `nbconvert <6` Do you know @yakutovicha? Are we risking breakage when `nbconvert` is updated?

2022-11-27 21:34 UTC, yakutovicha commented
> nbconvert

I remember nothing about this package. One needs to test...

2022-11-27 22:24 UTC, yakutovicha commented
> > I wonder was there a specific reason for this constraint? `nbconvert <6` Do you know @yakutovicha? Are we risking breakage when `nbconvert` is updated?
> 
> I remember nothing about this package. One needs to test...

btw, there is also https://github.com/aiidalab/aiidalab-widgets-base/issues/384.

2022-11-27 23:14 UTC, danielhollas commented
Thanks @yakutovicha, I was not aware of that issue. Couple days ago I also opened #392 which is related.

2022-11-27 23:17 UTC, danielhollas requested changes
I think we should take this step by step.

> The following packages are even in conflict and will override the deps which causes the Jupyter engine to fail, we need to pining version when we find future confliction.
    jupyter-client<7
    nbconvert<6
    aiidalab>=21.11.2 is already pinned in the stack

@unkcpz could you open a new PR which would only fix the dependencies for the current Docker stack, listed above? `aiida-core[atomic_tools]` is a separate discussion.

2022-11-28 10:07 UTC, unkcpz commented
> @unkcpz could you open a new PR which would only fix the dependencies for the current Docker stack, listed above? aiida-core[atomic_tools] is a separate discussion.

Sure, updated. I add `PyCifRW` explicitly since it is required by this package.

2022-11-28 12:35 UTC, danielhollas approved these changes
Thanks @unkcpz. I did a quick test locally and it looks good to me. Approving but we should wait until we release a new docker-stack version so that the tests are passing here.

2022-11-28 17:55 UTC, unkcpz commented
The firefox tests are expected to fail and PR #397 is for it, there are two chrome tests that also fail but I think if there are two passes then the implementation is correct.. I'll merge this and if anything happened I'll fix it afterward.

2022-11-28 17:56 UTC, merged

2022-11-28 22:46 UTC, yakutovicha commented
Sorry, I am late to the party. 

> * `aiidalab>=21.11.2` is already pinned in the stack

I am not 100% sure this is a good thing to do. AiiDAlab could be setup outside of the stack, and AWB does require aiidalab package to function.

2022-11-28 23:00 UTC, unkcpz commented
You are right, and I find the doc build always lack the necessary packages if `aiidalab` package is not explicitly installed. I add `aiidalab>=21.11.2` back in https://github.com/aiidalab/aiidalab-widgets-base/pull/397 to fix the doc build test.

2022-12-01 10:39 UTC, danielhollas commented on setup.cfg
> -    pandas~=1.0
@unkcpz I just noticed that you removed pandas here. Do you know where else it is coming from?

2022-12-01 10:40 UTC, danielhollas commented on setup.cfg
> -    pandas~=1.0
Ah, it seems it comes from `optimade-client`, never mind.