fix bug report to use the new return type of find_installed_packages
aiidalab/aiidalab-widgets-base pull request #446
Opened 2023-03-14 14:51 UTC by unkcpz

fixes #445

2023-03-14 14:54 UTC, danielhollas commented
@unkcpz just a quick question, is your fix compatible with both the old and new `aiidalab` package versions? I think it needs to be, otherwise it's a mess for the users.

2023-03-14 14:58 UTC, unkcpz commented
> @unkcpz just a quick question, is your fix compatible with both the old and new aiidalab package versions?

Nope, but I see your point. I'll make a change. Thanks for the head up.

2023-03-14 17:25 UTC, unkcpz commented
It support the old version of `aiidalab`. But the `test_fingerprint_parser` pass without hitting the correct code path. In the test, it still using the old aiidalab since we didn't release a new version yet.

This is a issue with unit test because of the `load_profile()` we used in `__init__.py`, I don't have very clear clue why that happened but that need the fix from aiida-core I assume. The workaround is moving the import clause into the test functions. @yakutovicha encounter the same issue in his PR, we need investigate more and then open the issue in aiida-core.

For this PR, I think it is ready to review.

2023-03-14 17:28 UTC, unkcpz commented
I also move the fixtures in this PR with are duplicate as @yakutovicha did in https://github.com/aiidalab/aiidalab-widgets-base/pull/441/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128
Let's discuss how we manage these on Thursday.

2023-03-14 18:10 UTC, yakutovicha commented
> I also move the fixtures in this PR with are duplicate as @yakutovicha did in https://github.com/aiidalab/aiidalab-widgets-base/pull/441/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128
> Let's discuss how we manage these on Thursday.

I wouldn't worry too much about this. If your PR is merged first, I will adapt mine. If mine - then the other way around. It is really about moving some chunk of code, nothing more than this.

2023-03-14 18:16 UTC, yakutovicha reviewed
This looks good to me. I let @danielhollas have a final look since you guys were discussing this before. If everything is OK - let's merge it.

2023-03-14 18:16 UTC, yakutovicha commented on tests/test_bug_report.py
> +# )
Is this comment still needed?

2023-03-14 22:24 UTC, danielhollas requested changes
I've thought about this a bit more, and I really don't like that we have this random coupling between AWB and the `aiidalab` package, especially since we're importing a function from utils, i.e. not really something one might consider stable public API. 
I think just the very existence of this PR makes this argument self-evident.

I am aware that this might not by _DRY_ or whatever, but let's be pragmatic here and define our own simplified local `find_installed_packages` (without using the Package class). WDYT?

2023-03-15 01:10 UTC, unkcpz commented on tests/test_bug_report.py
> +# )
```suggestion
```

2023-03-15 01:36 UTC, unkcpz commented on tests/test_bug_report.py
> +# )
Yep, removed.

2023-03-15 01:37 UTC, unkcpz commented
> I am aware that this might not by DRY or whatever, but let's be pragmatic here and define our own simplified local find_installed_packages (without using the Package class). WDYT?

I was worried about it not DRY, but after trying it is very clean. After all, we just need a very simple help function.

2023-03-15 13:59 UTC, danielhollas approved these changes
Thanks @unkcpz. I tested manually that this work with the latest `aiidalab` package.

Will you take care of cherry-picking this on the 1.x branch and releasing a new version?

2023-03-16 08:25 UTC, unkcpz commented
> Will you take care of cherry-picking this on the 1.x branch and releasing a new version?

Sure I'll do that now.

2023-03-16 08:29 UTC, merged