Restore backwards compatibility for some widgets
aiidalab/aiidalab-widgets-base pull request #471
Opened 2023-03-24 13:59 UTC by yakutovicha

fixes #426

2023-03-25 11:40 UTC, unkcpz requested changes
Thanks @yakutovicha for taking care of this. The changes are good. 
Although there is an issue caused by using threading with daemon as we discussed offline, I propose we ignore it for the moment.

```
03/25/2023 11:26:31 AM <2172657> sqlalchemy.pool.impl.QueuePool: [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "/opt/conda/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "/opt/conda/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

I spend some time try to figure it out and narrow down it with a minimal reproduce case. It can be reproduced when submit the process using test daemon, and having a separate threading query the database. 

The test can be like this:

```python
def test_process_monitor(
    multiply_add_process_builder_ready, daemon_client, await_for_process_completeness
):
    """Test ProcessMonitor with a simple `WorkChainNode`"""
    from aiidalab_widgets_base.process import ProcessMonitor

    process = engine.submit(multiply_add_process_builder_ready)
    widget = ProcessMonitor(value=process.uuid)
```

The `_monitor_process` method of `ProcessMonitor` just need to have a query as:

```python
    def _monitor_process(self, process_uuid):
        assert process_uuid is not None
        process = orm.load_node(process_uuid)
```

I assume this still comes from aiida in general not thread-safe, I think maybe we need help from Chris to dig the root out. I'll ask him and set a meeting for that, but this has to be after the 2.0 release of AWB.

2023-03-25 11:40 UTC, unkcpz commented on tests/test_process.py
> +
```suggestion
    daemon_client.stop_daemon(wait=True)
```

If use `daemon_client`, need to stop daemon explicitly after the test.

2023-03-25 11:45 UTC, danielhollas commented
@yakutovicha I will take a closer look at this, please wait before merging, thanks.

2023-04-03 09:33 UTC, danielhollas commented
>  Although there is an issue caused by using threading with daemon as we discussed offline, I propose we ignore it for the moment.

@unkcpz can you elaborate on this? Is this problem present also on master or only on this PR? If the latter, we should not merge this.
What aiida-core version have you seen it? I think there have been some issues with the daemon for version < 2.2.2

2023-04-03 09:50 UTC, danielhollas reviewed
tbh I am not very happy about the code here (and I realize I was the one pushing for this change, my apologies). The circular nature of the `value` and `process` traits makes the code very confusing and error prone imo. My original idea was to have a one-way flow from `process` to `value`, but that is not great either since they would not be in sync which might lead to bugs as well.

2023-04-03 13:24 UTC, danielhollas commented
@yakutovicha that is fine with me, since you anyway said we have currently control over all apps in the appstore.

Btw: the new test in this PR might be worthwhile merging.

I am travelling today back from Switzerland, should be available more tomorrow.

2023-04-03 17:23 UTC, unkcpz commented
> @unkcpz can you elaborate on this? Is this problem present also on master or only on this PR? If the latter, we should not merge this.
What aiida-core version have you seen it? I think there have been some issues with the daemon for version < 2.2.2

The error is shown in  https://github.com/aiidalab/aiidalab-widgets-base/pull/471#pullrequestreview-1357821001 and can be reproduce with the latest docker stack which running with aiida-core 2.2.2. 

It is not this PR which introduces the issue, it was there already. The tests will not failed but the error messages popped up showing the DB session is not properly shut down after the query. @yakutovicha and I suspect this might be the issue that causes the memory leak of the container we run for the moment.

2023-04-12 21:05 UTC, unkcpz commented
Seems we don't want to continue on this route. 
So @yakutovicha can you update the PR to leave only the test as @danielhollas suggested?

2023-04-26 09:12 UTC, yakutovicha commented
> Seems we don't want to continue on this route. So @yakutovicha can you update the PR to leave only the test as @danielhollas suggested?

yep, I just opened PR #478 with the test only.

2023-04-26 09:12 UTC, closed without merging