Add info box widgets with CSS stylesheets
aiidalab/aiidalab-widgets-base pull request #623
Opened 2024-07-09 06:17 UTC by edan-bainglass

This PR adds the following:

1. Loading of local SCSS/CSS stylesheets for easy/flexible styling
2. Info box widgets to provide in-app information to users

2024-07-12 12:17 UTC, edan-bainglass commented
@superstar54 @unkcpz can you guys have a look at the failed tests? I don't see how my changes could suddenly trigger the following error, which is failing several structure-related tests!

```
DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
```

2024-07-12 13:17 UTC, superstar54 commented
I just created an issue on this: https://github.com/aiidalab/aiidalab-widgets-base/issues/625

2024-07-12 13:18 UTC, edan-bainglass commented
@superstar54 I see. So we need to update on our end? I take it this is unrelated to my PR. I would rebase on top of an update PR once that's in?

2024-07-12 13:22 UTC, superstar54 commented
> Regarding an spglib update PR, do we need it? Can we instead pin to <2.5.0?

No idea yet.

2024-07-12 13:36 UTC, danielhollas commented
You can just add the DeprecationWarning to the list of ignored warnings in pyproject.toml

(We have configured pytest so that it turns any warnings into errors, maybe we should change it)

2024-08-21 17:07 UTC, superstar54 requested changes
Hi @edan-bainglass , thanks for the nice work.

2024-08-21 17:17 UTC, edan-bainglass commented on aiidalab_widgets_base/infobox.py
> +            file.write("existing-user")
I agree. This isn't a great approach. Username would be better, or some other uniquely identifying property. This was just a proof of concept. I was hoping someone with more knowledge of AiiDAlab could provide a better solution :)

2024-08-21 17:18 UTC, edan-bainglass commented on aiidalab_widgets_base/infobox.py
> +        custom_css = kwargs.pop("custom-css", "")
I actually had it like that initially but changed it for what I vaguely recall was a good reason. If I can't remember it in a day or so, I'll revert to this.

2024-08-21 20:10 UTC, danielhollas commented on aiidalab_widgets_base/infobox.py
> +        custom_css = kwargs.pop("custom-css", "")
Btw: I think the parameter should be called `cuatom_class`. ;-)

2024-08-22 10:33 UTC, edan-bainglass commented on aiidalab_widgets_base/infobox.py
> +        custom_css = kwargs.pop("custom-css", "")
I redesigned this part a bit. I think it is clearer. Let me know.

2024-08-22 10:34 UTC, edan-bainglass commented on aiidalab_widgets_base/infobox.py
> +            file.write("existing-user")
I really don't like how I've implemented it. Just needed a proof of concept. Open to suggestions. A cookie to the user's browser may be a good approach.

2024-08-22 11:53 UTC, edan-bainglass commented on aiidalab_widgets_base/infobox.py
> +            file.write("existing-user")
@giovannipizzi suggested we keep this as a local config file and had some ideas for its structure. I'll let him explain it.

2024-08-30 09:41 UTC, edan-bainglass commented
Moving this PR to the QE App for local testing. If all is good and approved for general use, `InfoBox` classes will move back to the widgets base.

2024-08-30 09:41 UTC, closed without merging