Migrate to ipywidgets 8.x
aiidalab/aiidalab-widgets-base pull request #644
Opened 2024-11-22 09:58 UTC by yakutovicha

fixes #473

2025-02-04 13:58 UTC, danielhollas reviewed
Whoops, I had some comments during the hackathon that I forgot to submit.

2025-02-04 14:38 UTC, yakutovicha commented
I can conclude that `uv` is drunk today:
![image](https://github.com/user-attachments/assets/3efef63a-6f9c-4f19-a851-0b0e8bf5c1e0)

2025-11-10 11:35 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +            select_panel.set_title(0, "Select structure")
Sure. But also https://github.com/MADICES/MADICES-2025/discussions/27. The API has changed. Unclear yet (need to test) if `titles` can be provided directly on `Tab` definition, but in any case, we can open a separate issue to update to the newer API of `.titles`.

2025-11-10 11:37 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +                ]  # ipywidgets 8.x
Since we're moving to 8, wouldn't it make more sense to do "try 8, except... do 7"?

2025-11-10 11:37 UTC, edan-bainglass commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
Seems unrelated. What was this about?

2025-11-10 11:39 UTC, edan-bainglass commented on tests/test_nodes.py
> +        assert open_node_in_app.tab.get_title(i) == expected_tab_titles[i]
Is this strictly needed for version 8, or a drive-by update?

2025-11-10 16:51 UTC, danielhollas commented
Thanks a ton for working on this @yakutovicha. Before merging I'd like to test this on my app once I am back from holidays next week. (and obviously somebody should test on QeApp)

2025-11-24 14:07 UTC, yakutovicha commented on setup.cfg
> -    widgetsnbextension<3.6.3
> See this issue [aiidalab/aiidalab-docker-stack#512](https://github.com/aiidalab/aiidalab-docker-stack/issues/512) Definitely will need testing.

I think this particular issue is related to the unpredictable behaviour of the `ipw.Output` widget. I replaced it with `ipw.VBox`, which is stable: https://github.com/aiidalab/aiidalab-qe/pull/1425

2025-11-24 14:12 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +            select_panel.set_title(0, "Select structure")
I am confused by the link and the comment. The link leads to ro-crate discussions that have nothing to do with the widgets. The `set_title` method works for both: ipywidgets 7.x and 8.x, it just behaves slightly differently.

2025-11-24 14:20 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
In ipywidgets 8, the default value for the `selected_index` is `None`, which means no tab is selected. Without this change the widget fails to load.

2025-11-24 15:33 UTC, yakutovicha commented
@danielhollas, as discussed during the meeting, please go ahead with the PR review.

2025-11-24 16:21 UTC, danielhollas commented on tests/test_nodes.py
> +        assert open_node_in_app.tab.get_title(i) == expected_tab_titles[i]
The original code relied on a private attribute `_title` so this is clearly better, even if not needed.

2025-11-24 16:24 UTC, danielhollas commented on setup.cfg
> -    widgetsnbextension<3.6.3
Interesting, but does that mean that apps using Output will be broken? Will our guideline be to never use it?

2025-11-24 16:25 UTC, danielhollas commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
Does the `ipw.link` need to happen after the `super().init()` call? Maybe just add a short comment about why this is so that this code does not get moved in the future.

2025-11-24 16:27 UTC, danielhollas commented on tests/test_nodes.py
>      assert len(open_node_in_app.tab.children) > 0
```suggestion
    assert len(open_node_in_app.tab.children) == 3
```

2025-11-24 16:28 UTC, danielhollas commented on tests/test_nodes.py
> +        assert open_node_in_app.tab.get_title(i) == expected_tab_titles[i]
Slightly shorter (assuming that we assert that the lengths are the same, as per suggestion above)
```suggestion
    for i, title in enumerate(expected_tab_titles):
        assert open_node_in_app.tab.get_title(i) == title
```

2025-11-24 16:56 UTC, danielhollas commented on aiidalab_widgets_base/structures.py
> +                ]  # ipywidgets 8.x
I was confused by the function name, can it be more explicit, like `get_fname_and_bytes`? 

Also, let's just return the first item from the list and assert that there is only 1 item. That should be guaranteed, since we set `multiple=False` in the widget constructor, so the user cannot upload more than one file. 

In the new implementation you dropped the `self.file_upload.value.clear()` call. Is it not needed?

Maybe something like:

```suggestion
        def get_fname_and_bytes(value):
            """This function ensures backwards compatibility w.r.t. ipywidgets 7.x
            https://ipywidgets.readthedocs.io/en/latest/user_migration_guides.html#fileupload            
            """
            assert len(value) == 1
            try:
                # ipywidgets 7.x
                for fname, item in value.items():
                    return fname, item["content"]
            except AttributeError:
                # ipywidgets 8.x
                for f in value:
                    return f["name"], f.content.tobytes())
```

2025-11-24 16:58 UTC, danielhollas commented on aiidalab_widgets_base/structures.py
> +        self.structure = self._read_structure(fname, item)
If the suggestion above is taken this becomes

```suggestion
        fname, item = get_fname_and_bytes(change["new"])
        self.structure = self._read_structure(fname, item)
        self.file_upload.value.clear()
```
Do we need the "clear()" call?

2025-11-24 17:08 UTC, danielhollas requested changes
@yakutovicha thanks so much on working on this! I left a couple of minor comments.
I'll do some manual testing tomorrow (or later in the week depending on time).

2025-12-02 12:45 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        self.structure = self._read_structure(fname, item)
> Do we need the "clear()" call?

Actually, we don't - it has no effect in ipywidgets 7.x and fails in ipywidgets 8.x, so definitely not needed. Done in https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/10b21f5e9b393f3b37d5fa9fdca7cc8ef845be8d

2025-12-02 12:56 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +            select_panel.set_title(0, "Select structure")
Sorry, I guess I had a different link copied at the time. I meant this - https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#tabs.

This is not priority at the moment, nor am I sure if this is wise to consider. We can proceed with `set_title`, as it is cross-version compatible.

2025-12-02 12:56 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +                ]  # ipywidgets 8.x
I honestly don't know. It seems unimportant to me. 

Additionally, since the current codebase relies mostly on 7.x, it makes sense to check for it first. But this is just a speculation.

2025-12-02 12:57 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +            edit_panel.set_title(0, "Edit structure")
Version 7 didn't? Odd. Seems like it would just be a Python error.

2025-12-02 13:00 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +            edit_panel.set_title(0, "Edit structure")
🤷

2025-12-02 13:03 UTC, edan-bainglass commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
Failed to load, or loads in a closed state?

2025-12-02 13:04 UTC, edan-bainglass commented on tests/test_nodes.py
> +        assert open_node_in_app.tab.get_title(i) == expected_tab_titles[i]
Clean! I support this suggestion.

2025-12-02 13:07 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +                ]  # ipywidgets 8.x
Carry on 😅

2025-12-02 13:08 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +            edit_panel.set_title(0, "Edit structure")
Here is a small demonstration:
<img width="381" height="333" alt="image" src="https://github.com/user-attachments/assets/157c501d-ed96-46b2-81c8-440b6fc4776e" />

2025-12-02 13:10 UTC, yakutovicha commented on setup.cfg
> -    widgetsnbextension<3.6.3
> Will our guideline be to never use it?

Yes, that would be my proposal. Happy to make a bunch of PRs to replace `ipw.Output` with `ipw.VBox`.

2025-12-02 13:36 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
> Failed to load, or loads in a closed state?

I wrote something strange above, sorry. Indeed, the widget is loaded in a closed state. We have some tests that check that the 0th element is opened by default. Should we remove that test and accept the default behaviour of the `Accordion` widget?

- In ipywidgets 7.x, 0th element of the accordion is opened
- In ipywidgets 8.x, all elements of the accordion are closed

2025-12-02 13:38 UTC, yakutovicha commented on tests/test_nodes.py
> +        assert open_node_in_app.tab.get_title(i) == expected_tab_titles[i]
merged in https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/cf36c574bae8fad104894952780e2ba68b7ea2d2

2025-12-02 13:42 UTC, edan-bainglass commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
I think so. At least in the QE app, I keep it closed by default. Let the user choose if they wish to have it open.

2025-12-02 13:53 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
> Let the user choose if they wish to have it open.

done in https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/8c7426d45cfefd8666b7e7efc5f9ea06f202c535 and https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/c55e4def46d7a8efce130eb99fa290ff1f0e4a3d.

2025-12-02 14:14 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +            edit_panel.set_title(0, "Edit structure")
Very odd! Bad design on their part. I guess they agree, as they removed it.

2025-12-02 14:29 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        self.selected_index = 0
> Does the `ipw.link` need to happen after the `super().init()` call? Maybe just add a short comment about why this is so that this code does not get moved in the future.

Actually, not, but it needs to happen after all the other widgets are created, cause changing the `selected_index` trait will request their updates. Updated here: https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/bb23879d50446a7d805ae19e3318192e82daa324

2025-12-02 14:42 UTC, danielhollas commented on aiidalab_widgets_base/wizard.py
> +        print("After link")
stray debugging statement :-)

2025-12-02 14:43 UTC, yakutovicha commented
@danielhollas, @edan-bainglass, @cpignedoli, please be informed that this change is somewhat "contagious".

If your current version of ipywidgets is `7.7.x`, it will be updated to `7.8.x`. Unfortunately, there seems to be no way back from 7.8 to 7.7 (at least I didn't find). After you downgrade, the widgets won't appear any longer. 

So it seems like only `7.8` can be swapped with `8.x` back and forth without too much burden.

Bottom line is - don't test this change in a production environment.

2025-12-02 14:44 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        print("After link")
sorry

2025-12-02 14:48 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        print("After link")
https://github.com/aiidalab/aiidalab-widgets-base/pull/644/commits/ee5a55c28bb266240cd8673fb6c671572c7ca299

2025-12-02 15:21 UTC, danielhollas commented
> If your current version of ipywidgets is 7.7.x, it will be updated to 7.8.x. Unfortunately, there seems to be no obvious way back from 7.8 to 7.7 (at least I didn't find). After you downgrade, the widgets won't appear any longer.

Thanks for a thorough testing @yakutovicha. This seems like a very important point and we will need to think how we release this change (which AWB version?) so that we do not break users. 
Importantly, even in the latest full-stack image we have 7.7 installed.

@yakutovicha there are in the end only few code changes here. Why was it necessary to increase the minimum ipywidget version? Is there any way that we can still support 7.7.x?

2025-12-03 13:03 UTC, yakutovicha commented
> Thanks for a thorough testing @yakutovicha. This seems like a very important point and we will need to think how we release this change (which AWB version?) so that we do not break users.

We tested this version of the app in various environments, and it seems that the 7.8 version is not super stable either, as some widgets randomly disappear. This makes the task of supporting both 7.x and 8.x quite challenging.

Instead, what we would do better is perform a proper migration to ipywidgets 8.x, making a major release of awb (3.0.0) together with a new release of the home app that depends on awb 3.x. This will be accompanied by a migration guide.

In the meantime, we can also remove awb from the aiidalab app registry, as discussed in https://github.com/aiidalab/aiidalab-widgets-base/issues/550.

We quickly discussed with @edan-bainglass, and he agrees.

2025-12-03 13:33 UTC, danielhollas commented
@yakutovicha thanks, makes sense. Should this migration also be tied to the switch from Python 3.9 to 3.11 and to nbclassic? In terms of managing the docker images that might be the cleanest option, since users can then pin their images to `python-3.9.13` tag to ensure their production environments won't break once we release everything.

2025-12-04 10:45 UTC, yakutovicha commented
> @yakutovicha thanks, makes sense. Should this migration also be tied to the switch from Python 3.9 to 3.11 and to nbclassic? In terms of managing the docker images that might be the cleanest option, since users can then pin their images to `python-3.9.13` tag to ensure their production environments won't break once we release everything.

As far as I understand, they are not strictly dependent on each other - ipywidgets 8 can work in Python 3.9 without problems, so I am not entirely sure it is a good idea, as it will add another waiting factor. 

At the same time, AiiDA is dropping Python 3.9 in the next minor release (2.8.x), and we have the [aiida tag](https://github.com/aiidalab/aiidalab-docker-stack/pkgs/container/full-stack/478312909?tag=aiida-2.7.1) in our aiidalab-docker-containers containers. We can bind aiida and aiidalab Python migration. Shall we?

2025-12-04 11:17 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +            select_panel.set_title(0, "Select structure")
> The API has changed. Unclear yet (need to test) if `titles` can be provided directly on `Tab` definition, but in any case, we can open a separate issue to update to the newer API of `.titles`.

Since we are dropping ipywidgets 7.x, I implemented your request: 3b2856cfdca230b206fe33a31a08a7e051b065d6

2025-12-04 13:45 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +            titles=["Import structure"] if importers else [],
This is so much nicer!

2025-12-04 13:47 UTC, edan-bainglass commented on aiidalab_widgets_base/structures.py
> +        self.structure = self._read_structure(file["name"], file["content"])
What happens if the user selects a file, then realizes they meant to upload a different one? At this point, the loader is at 1 already, so it raises an error? I vaguely recall working on this part due to a bug in the QE app.

2025-12-04 13:48 UTC, edan-bainglass commented on aiidalab_widgets_base/wizard.py
> +        ipw.link((self.accordion, "selected_index"), (self, "selected_index"))
Why?

2025-12-04 13:48 UTC, edan-bainglass commented on tests/test_wizard.py
> +    widget.accordion.selected_index = 0  # Ensure first step is selected.
Why the move?

2025-12-04 13:49 UTC, edan-bainglass reviewed
Thanks @yakutovicha. Have a look at my comment regarding the file uploader.

2025-12-04 21:55 UTC, yakutovicha commented on tests/test_wizard.py
> +    widget.accordion.selected_index = 0  # Ensure first step is selected.
just is just to ensure the test flow is running as expected

2025-12-04 21:56 UTC, yakutovicha commented on aiidalab_widgets_base/wizard.py
> +        ipw.link((self.accordion, "selected_index"), (self, "selected_index"))
cause the linkage will trigger the widgets updates, and if they don't exist, the update will raise an exception.

2025-12-04 21:57 UTC, yakutovicha commented on aiidalab_widgets_base/structures.py
> +        self.structure = self._read_structure(file["name"], file["content"])
This is still possible. We only do not allow selecting multiple files at the same time.

2025-12-05 10:11 UTC, merged

2025-12-05 11:16 UTC, yakutovicha commented
> Sorry for post merge comment, the changes here looks good, but I think it would be nice to get a minor version release out before doing this, there are a fair amount of commits on main and some.of them bug fixes. (Happy to prepare a release)

sure, go ahead